### ISSUE TITLE
Idée style : Menu "BLOG" highlighted si dans article

### ISSUE THREAD

**Issue by hgcl** [robinmetral/clarale.com#6]
Faire en sorte que le menu "BLOG" s'affiche en rouge (avec le gros point en-dessous) lorsqu'on est en train de lire article.

**Comment by robinmetral** [comment]
:+1: 
C'était prévu, merci de l'avoir listée ici :slightly_smiling_face:

**Comment by robinmetral** [comment]
Je ferme, on verra pour réouvrir si on réouvre le blog!
